import { SocialMediaPlatform } from "@/shared/types/entities/SocialMediaPlatforms";
import {
  FaApple,
  FaDiscord,
  FaFacebook,
  FaInstagram,
  FaTiktok,
  FaSpotify,
  FaPatreon,
  FaTwitter,
  FaYoutube,
} from "react-icons/fa6";

export const SOCIAL_PLATFORMS: SocialMediaPlatform[] = [
  {
    label: "Apple Music",
    value: "appleMusicUsername",
    active: "appleMusic",
    prefix: "https://music.apple.com/us/artist/",
    type: "APPLE_MUSIC",
    icon: FaApple,
  },
  // {
  //   label: "Discord",
  //   value: "discordUsername",
  //   prefix: "https://discord.com/",
  //   icon: FaDiscord,
  // },
  {
    label: "Facebook",
    value: "facebookUsername",
    active: "facebook",
    prefix: "https://facebook.com/",
    type: "FACEBOOK",
    icon: FaFacebook,
  },
  {
    label: "Instagram",
    value: "instagramUsername",
    active: "instagram",
    prefix: "https://instagram.com/",
    type: "INSTAGRAM",
    icon: FaInstagram,
  },
  {
    label: "Patreon",
    value: "patreonUsername",
    active: "patreon",
    prefix: "https://patreon.com/",
    type: "PATREON",
    icon: FaPatreon,
  },
  {
    label: "Spotify",
    value: "spotifyUsername",
    active: "spotify",
    prefix: "https://open.spotify.com/artist/",
    type: "SPOTIFY",
    icon: FaSpotify,
  },
  {
    label: "TikTok",
    value: "tiktokUsername",
    active: "tiktok",
    prefix: "https://tiktok.com/@",
    type: "TIKTOK",
    icon: FaTiktok,
  },
  {
    label: "Twitter/X",
    value: "twitterUsername",
    active: "twitter",
    prefix: "https://x.com/",
    type: "TWITTER_X",
    icon: FaTwitter,
  },
  {
    label: "YouTube",
    value: "youtubeUsername",
    active: "youtube",
    prefix: "https://youtube.com/",
    type: "YOUTUBE",
    icon: FaYoutube,
  },
];
